package net.sitina.projectEuler.problems.p002;

public class Problem002 {

	// http://projecteuler.net/problem=2
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		System.out.println("The sum is " + findSum(4000000));
	}
	
	/**
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */
	public static long findSum(long limit) {
		long p1 = 2;
		long p2 = 1;
		long tmp;
		long sum = 2;
		
		while (p1 < limit) {
			tmp = nextNum(p1, p2);
			p2 = p1;
			p1 = tmp;			
			sum += (tmp % 2 == 0) ? tmp : 0;
		}
		
		return sum;
	}
	
	private static long nextNum(long p1, long p2) {
		return p1 + p2;
	}
	
	

}
